### ISSUE TITLE
Does not work in Mist, cannot access Mist's web3 provider

### ISSUE THREAD

**Issue by graup** [uzyn/web3-loader#13]
https://github.com/uzyn/web3-loader/blob/b9b0efdadfce68ab521421838207d63da490b84e/lib/web3-helper.js#L8

I think this doesn't work. After being compiled by Webpack, this code ends up in its own function to which `var web3;` is scoped to. Thus is is impossible to access `web3.currentProvider` provided by Mist.

Maybe we can check for `window.web3` instead?

**Comment by uzyn** [comment]
Thanks for the PR.
